application: yelp-pushmaster
version: 28
runtime: python
api_version: 1

handlers:
- url: /static/(.+)
  static_files: www/static/\1
  upload: www/static
  expiration: "365d"

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: .*
  script: main.py
  login: required

