application: yelp-pushmaster
version: 11
runtime: python
api_version: 1

handlers:
- url: /([^/]+/)?(css|js|images)/(.+)
  static_files: www/\2/\3
  upload: www/(css|js|images)/(.+)
  expiration: "365d"

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: .*
  script: main.py
  login: required

